import type { Metadata } from 'next'
import { Poppins, Lora } from 'next/font/google'
import './globals.css'

export const poppins = Poppins({
  weight: ['400', '500'],
  subsets: ['latin'] 
})

export const lora = Lora({
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  )
}
